trainingInput:
  hyperparameters:
    goal: MINIMIZE
    hyperparameterMetricTag: "my_loss"
    maxTrials: 3
    maxParallelTrials: 3
    enableTrialEarlyStopping: True
    params:
      - parameterName: batch-size
        type: DISCRETE
        discreteValues:
          - 32
          - 64
          - 128
